//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piaoju.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class detailsEntities : DbContext
    {
        public detailsEntities()
            : base("name=detailsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dtproperties> dtproperties { get; set; }
        public DbSet<Tjournals> Tjournals { get; set; }
        public DbSet<Toperator> Toperator { get; set; }
        public DbSet<Txueyuan> Txueyuan { get; set; }
        public DbSet<Tbianma> Tbianma { get; set; }
        public DbSet<Tzhidian> Tzhidian { get; set; }
        public DbSet<Tzhidian1> Tzhidian1 { get; set; }
        public DbSet<Tdetails> Tdetails { get; set; }
    }
}
