//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piaoju.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tdetails
    {
        public string bianm { get; set; }
        public string xueyh { get; set; }
        public string baomd { get; set; }
        public string type { get; set; }
        public string man { get; set; }
        public string shoukfs { get; set; }
        public decimal money { get; set; }
        public string moneyUpper { get; set; }
        public System.DateTime Kaipri { get; set; }
        public System.DateTime riqi { get; set; }
        public string @operator { get; set; }
        public string operator_name { get; set; }
        public string memo { get; set; }
    }
}
