//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piaoju.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tjournals
    {
        public string id { get; set; }
        public string @operator { get; set; }
        public string operator_name { get; set; }
        public System.DateTime riqi { get; set; }
        public string thing { get; set; }
    }
}
