//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piaoju.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toperator
    {
        public string bianm { get; set; }
        public string password { get; set; }
        public string xingming { get; set; }
        public string xingbie { get; set; }
        public string power { get; set; }
        public string state { get; set; }
    }
}
