//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jiax.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jiaxEntities : DbContext
    {
        public jiaxEntities()
            : base("name=jiaxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Txueyuan> Txueyuan { get; set; }
        public DbSet<Tzidian> Tzidian { get; set; }
        public DbSet<Tzidianlst> Tzidianlst { get; set; }
    }
}
