//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jiax.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Txueyuan
    {
        public string Xuey_ID { get; set; }
        public string Xingming { get; set; }
        public string Xingbie { get; set; }
        public Nullable<System.DateTime> Chusrq { get; set; }
        public string Zhengjzl { get; set; }
        public string Shenfhm { get; set; }
        public string Zanzzhm { get; set; }
        public string Zhaop { get; set; }
        public string Diqu { get; set; }
        public string Lianxdz { get; set; }
        public string Zhusdz { get; set; }
        public string Dianh { get; set; }
        public string Youzbm { get; set; }
        public string Shenqzl { get; set; }
        public string Xianzcx { get; set; }
        public string Shenqcx { get; set; }
        public string Tijian { get; set; }
        public Nullable<System.DateTime> Riqi { get; set; }
        public string ZhiwenA { get; set; }
        public string ZhiwenB { get; set; }
        public string Danganbh { get; set; }
        public string Xuey_Ic { get; set; }
        public string Mima { get; set; }
        public string Xueyh { get; set; }
        public string Xuexzt { get; set; }
        public string Shenhzt { get; set; }
        public string Qici { get; set; }
        public Nullable<System.DateTime> Kaibrq { get; set; }
        public string Yungqc { get; set; }
        public string Xueyz { get; set; }
        public string Jieyz { get; set; }
        public string Baom_ID { get; set; }
        public string Jiax { get; set; }
        public string Jianl { get; set; }
        public string Xingbie_sm { get; set; }
        public string Zhengjzl_sm { get; set; }
        public string Diqu_sm { get; set; }
        public string Shenqzl_sm { get; set; }
        public string Xianzcx_sm { get; set; }
        public string Shenqcx_sm { get; set; }
        public string Tijian_sm { get; set; }
        public string Shenhzt_sm { get; set; }
        public string Xuexzt_sm { get; set; }
        public string Jiax_sm { get; set; }
        public string Zwapic { get; set; }
        public string Zwbpic { get; set; }
        public Nullable<System.DateTime> jieyrq { get; set; }
        public Nullable<System.DateTime> Tuixrq { get; set; }
        public string Jinengzmbh { get; set; }
        public Nullable<System.DateTime> Jinengzmrq { get; set; }
        public string Guddh { get; set; }
        public string Baomd { get; set; }
        public string Jiaxmc { get; set; }
        public string Jiesr { get; set; }
        public Nullable<System.DateTime> Weisjhrq { get; set; }
        public string ycode { get; set; }
    }
}
